### ISSUE TITLE
Indent region in using formatR::tidy_source()

### ISSUE THREAD

**Issue by walmes** [basille/.emacs.d#1]
Hi Mathieu.

I saw a lot of references to your `ess-indent-region-as-R-function.el` file. I include your function to my `.emacs`. I like to use the function [`formatR::tidy_source()`](https://cran.r-project.org/web/packages/formatR/vignettes/formatR.html) to format R scripts. This function has arguments to control output that are very useful. So, as a try, I used `tidy_source()` in a modification of your function. This code is available on https://github.com/walmes/emacs/blob/emacs24.5/functions.el#L397. I named `ess-indent-region-with-formatR-tidy-source`. Maybe this can interest you. Your `.emacs` helped me a lot. Thank you.

**Comment by basille** [comment]
Thanks Walmes, it's good to know that some of my stuff is actually useful.

Your modification is very interesting! Especially to keep comments. However, for a reason, I'm getting weird errors that I have to understand.
