### ISSUE TITLE
ido-better-felx unavailible

### ISSUE THREAD

**Issue by Honigmelone** [basille/.emacs.d#2]
The following message is displayed at a fresh emacs 24.5 start up with your init.el after installing "use-package": 

Error (use-package): ido :config: Package `ido-better-flex-' is unavailable

I haven't found it in any archive using M-x list-packages, only separately on github. 
https://github.com/vic/ido-better-flex
It seems like it is still on Marmalade:
https://marmalade-repo.org/packages/ido-better-flex

**Comment by basille** [comment]
Indeed, this package seems completely outdated... Two things to try then:
- Standard IDO flex matching (enabled by `ido-enable-flex-matching t`)
- [flx-ido](https://github.com/lewang/flx), which may be loaded with something like:

``` lisp
    (use-package flx-ido
      :ensure t
      :init (flx-ido-mode))
```

(not tested)

Thanks for using this init.el! To be honest, I didn't know anyone was even looking at it :)
