### ISSUE TITLE
org-ref

### ISSUE THREAD

**Issue by nistara** [basille/.emacs.d#3]
Hello Dr. Basille, 
I wonder if you've considered org-ref in your emacs workflow: https://github.com/jkitchin/org-ref
It's a really nice add-on to the org-mode workflow! 
Regards

**Comment by basille** [comment]
Hey Nistara,

Currently not! But my org config is really suboptimal, and certainly the one point that would need some serious thoughts and cleaning. Admittedly too, I'm not using org-mode anywhere near what I'd like to do, so it's very much still a work in progress. I'll keep an eye on org-ref, thanks!
